### ISSUE TITLE
复现

### ISSUE THREAD

**Issue by 1-zym** [leeyegy/TokenPose#15]
作者你好，我使用你的代码仓库配置，复现Tokenpose-B，但是精度低了一点，请问是不是配置有问题啊

**Comment by leeyegy** [comment]
是否可以提供更详细的信息呢？比如训练数据集、精度结果、配置参数等等

**Comment by 1-zym** [comment]
> 是否可以提供更详细的信息呢？比如训练数据集、精度结果、配置参数等等

数据集:COCO 2017 ，在COCO验证集精度结果为74.1，配置参数，yaml文件只改了GPU，用的是两张A40，pytorch版本为1.12.1+cu116
