### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by MikuuGithub** [leeyegy/TokenPose#5]
您好，非常感谢您的开源work，我想知道是否会提供TokenPose-L/D24的预训练模型？我非常钦佩它拥有如此高的性能，迫不及待想要试一试。

**Comment by leeyegy** [comment]
感谢您的关注，由于代码经过重构，之前的预训练模型并不能直接加载因此暂时没有公布。后续有空我会将预训练模型进行转化适配到现在的代码后进行开源。不过，相信基于现在的代码，也很容易进行复现实验。

**Comment by MikuuGithub** [comment]
非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeyegy/TokenPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leeyegy/TokenPose] 预训练模型 (Issue #5)





 
感谢您的关注，由于代码经过重构，之前的预训练模型并不能直接加载因此暂时没有公布。后续有空我会将预训练模型进行转化适配到现在的代码后进行开源。不过，相信基于现在的代码，也很容易进行复现实验。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
