### ISSUE TITLE
About the inference.py

### ISSUE THREAD

**Issue by MikuuGithub** [leeyegy/TokenPose#7]
我发现本项目中没有提供推理代码，请问是否可以用deep-high-resolution-net.pytorch中的inference.py来实现本项目中模型的推理？

**Comment by leeyegy** [comment]
plz refer to lib/core/inference.py

**Comment by MikuuGithub** [comment]
Thanks for your reply.And I also want to know about the speed of inference(FPS)?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeyegy/TokenPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 凌晨0:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leeyegy/TokenPose] About the inference.py (Issue #7)





 
plz refer to lib/core/inference.py
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
